# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homicide',
            name='status_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='homicide',
            name='x',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='homicide',
            name='y',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
