# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yakima', '0004_homicide_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homicide',
            name='story',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homicide',
            name='year',
            field=models.IntegerField(default=2016),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homicide',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
